name: "Mondoo Kubernetes Cluster Action"
description: "Scan Kubernetes clusters for vulnerabilities and misconfigurations with Mondoo"
branding:
  icon: "shield"
  color: "purple"
inputs:
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  risk-threshold:
    description: >-
      If any risk is greater or equal to this, exit status is 1. (default "0" - job continues regardless of the score returned by a scan).
    default: "101"
    required: false
  service-account-credentials:
    description: "Base64 encoded service account credentials used to authenticate with Mondoo Platform"
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec:12"
  args:
    - scan
    - k8s
    - --output
    - ${{ inputs.output }}
    - --risk-threshold
    - ${{ inputs.risk-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
  env:
    MONDOO_CONFIG_BASE64: ${{ inputs.service-account-credentials }}
